special_char_map = {
    "period": ".",
    "comma": ",",
    "question mark": "?",
    "exclamation mark": "!",
    "colon": ":",
    "semicolon": ";",
    "apostrophe": "'",
    "quotation mark": '"',
    "dash": "-",
    "hyphen": "-",
    "parentheses": "()",
    "brackets": "[]",
    "braces": "{}",
    "ellipsis": "...",
    "plus sign": "+",
    "minus sign": "-",
    "multiplication sign": "×",
    "division sign": "÷",
    "equals sign": "=",
    "less than": "<",
    "greater than": ">",
    "percent sign": "%",
    "dollar sign": "$",
    "euro sign": "€",
    "pound sign": "£",
    "yen sign": "¥",
    "yuan sign": "元",
    "rupee sign": "₹",
    "won sign": "₩",
    "ampersand": "&",
    "at sign": "@",
    "number sign": "#",
    "asterisk": "*",
    "caret": "^",
    "tilde": "~",
    "backslash": "\\",
    "pipe": "|",
    "tab": "\t",
    "newline": "\n",
    "heart": "♥",
    "star": "★",
    "checkmark": "✓",
    "bullet point": "•",
    "copyright symbol": "©",
    "trademark symbol": "™",
    "registered trademark symbol": "®"
}